export const enum KEYS {
    C = "C",
    X = "X",
    Z = "Z",
    Y = "Y",
    A = "A",
    G = "G",
    L = "L",
    F = "F",
    D = "D",
    B = "B",
    MINUS = "-",
    EQUAL = "=",
    DIGIT_0 = "0",
    DELETE = "DELETE",
    UP = "ARROWUP",
    PAGEUP = "PAGEUP",
    PAGEDOWN = "PAGEDOWN",
    DOWN = "ARROWDOWN",
    LEFT = "ARROWLEFT",
    RIGHT = "ARROWRIGHT",
    ENTER = "ENTER",
    SPACE = " ",
    TAB = "TAB",
    BACKSPACE = "BACKSPACE"
}
